Set up CD workflow (#17)
* set up CD workflow

* update getAddressToAmountFunded to getAmountFundedByAddress

* update deploy command

* comment the path filter just to trigger the pipeline

* update cd workflow

* fix typos

* deploy and verify in the same step

* add exit commands

* reduce timeout to 1min

* only trigger pipeline on contracts update

* remove run.js

* rename scripts folder into deploy

* update msgs

* fix typo

* enable deploy to fuji job to fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,10 @@
 name: CI Workflow
-on: push
+
+on:
+  push:
+    paths:
+      - 'contracts/*.sol'
+
 jobs:
   # Hardhat CI workflow.
   # It installs the project dependencies as well as hardhat and it compiles, tests and deploys the smart contracts.
@@ -20,8 +25,42 @@ jobs:
       run: npx hardhat compile
     - name: 🧪 Test
       run: npx hardhat test
-    - name: 🚀 Deploy
-      run: npx hardhat run scripts/deploy.js
+    - name: 🏠 Deploy to localhost
+      run: npx hardhat run deploy/fund.js
+    - name: 🚀 Deploy and verify contract to fuji testnet
+      run: |
+        # Define useful variables.
+        export GREEN="\033[1;32m"
+        export RED="\033[1;31m"
+        export RESET="\033[0m"
+
+        # Deploy to fuji testnet.
+        echo "> Deploying contract on fuji testnet..."
+        export CONTRACT_ADDRESS=$(CI=true npx hardhat run deploy/fund.js --network fuji)
+        if [[ -z "$CONTRACT_ADDRESS" ]]; then
+            echo -e "${RED}> Error while deploying the contract.${RESET}"
+            exit 1
+        else
+            echo -e "${GREEN}> Contract deployed at ${CONTRACT_ADDRESS}.${RESET}"
+        fi
+
+        # Verify contract on testnet.snowtrace.io.
+        export TIMEOUT=$(date -d "+1 min")
+        echo -e "> Verifying contract...\n"
+        until npx hardhat verify --network fuji $CONTRACT_ADDRESS
+        do
+            if [[ $(date) > $TIMEOUT ]]; then
+                echo -e "${RED}\n> Deadline expired (1 min)${RESET}"
+                exit 1
+            fi
+            echo -e "${RED}\n> Retrying in 10 seconds...\n${RESET}"
+            sleep 10
+        done
+      continue-on-error: true     
+    env:
+      FUJI_PRIVATE_KEY: ${{ secrets.FUJI_PRIVATE_KEY }}
+      SNOWTRACE_API_KEY: ${{ secrets.SNOWTRACE_API_KEY }}
+      COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
   
   # Audit CI workflow.
   # It installs python, slither-analizer and mythril before performing static analysis on solidity files.
